site_name: PostalPoint Plugin Development
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: blue
  logo: assets/logo.svg
  favicon: https://postalpoint.app/images/favicon-voxel.png
  features:
    - content.code.copy
extra:
  homepage: https://postalpoint.app
  analytics:
    provider: custom
    url: analytics.netsyms.net
    siteid: 57
extra_css:
  - assets/styles.css
plugins:
  - privacy
  - search
markdown_extensions:
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: 'docs/'
  - pymdownx.superfences
